version: "3.9"

services:
  app:
    image: diyorbek2001/myapp
    container_name: myapp
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q0-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3